#!/bin/sh

case "$1" in
    configure)
        if adduser --quiet --system --group --no-create-home cloudbd; then
	    >/usr/lib/tmpfiles.d/cbd.conf echo 'd /var/run/cloudbd 0770 cloudbd cloudbd - -'
	fi
        ;;
    abort-upgrade|abort-remove|abort-deconfigure)
        # We need not do anything.
        ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 0
        ;;
esac

#DEBHELPER#

exit 0
